# Generated by Django 4.1.6 on 2023-02-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
